package jp.cobolinsight.app.rules;

import jp.cobolinsight.app.cli.LintRunner;
import jp.cobolinsight.core.finding.Finding;
import jp.cobolinsight.core.rule.Rule;
import jp.cobolinsight.rules.BuiltinRules;
import jp.cobolinsight.rules.RuleSet;
import jp.cobolinsight.rules.RulesFile;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The measurement harness behind {@code corpus/rule-hits.md}.
 *
 * <p>It runs every built-in rule — the {@code rules.json} of the machine is ignored and every rule
 * is forced on, so a rule that ships disabled is still measured — over three asset folders.
 * {@code samples/} carries intentional defects listed in {@code samples/expected-findings.tsv}.
 * {@code corpus/} is deliberately defect-free, so a finding there is a false positive by
 * construction. {@code samples-field/} is field-style code with both a list of seeded defects and
 * a baseline. On a folder that carries a baseline, every finding has to be either an expected
 * defect or written down in that folder's {@code baseline.tsv} with a reason. The test fails when
 * a hit is in neither, and when a baseline entry no longer fires: noise then arrives as a
 * reviewable diff rather than as a silent drift. {@code samples/} carries no baseline and is held
 * to its expected rows by {@code ExpectedFindingsAcceptanceTest} alone.
 *
 * <p>It also gates coverage: a rule that is on by default must have at least one positive fixture,
 * either a row in one of the {@code expected-findings.tsv} files or its id in a test under the
 * {@code rules} module.
 */
class RuleEvaluationReportTest {

    private static final Path REPO = Path.of("..", "..", "..").toAbsolutePath().normalize();
    private static final Path RULES_TESTS =
            REPO.resolve("src/engine/rules/src/test/java/jp/cobolinsight/rules");
    private static final Path REPORT = REPO.resolve("corpus/rule-hits.md");

    private static final String BEGIN = "<!-- generated by RuleEvaluationReportTest: begin -->";
    private static final String END = "<!-- generated by RuleEvaluationReportTest: end -->";

    /** One measured asset folder. {@code expected} and {@code baseline} are null where the folder has none. */
    private record Folder(String name, Path dir, List<Path> copybooks, Path expected, Path baseline) {
    }

    private static final List<Folder> FOLDERS = List.of(
            new Folder("samples", REPO.resolve("samples"), List.of(REPO.resolve("samples/copybook")),
                    REPO.resolve("samples/expected-findings.tsv"), null),
            new Folder("corpus", REPO.resolve("corpus"), List.of(REPO.resolve("corpus")), null,
                    REPO.resolve("corpus/baseline.tsv")),
            new Folder("samples-field", REPO.resolve("samples-field"),
                    List.of(REPO.resolve("samples-field/batch"), REPO.resolve("samples-field/online")),
                    REPO.resolve("samples-field/expected-findings.tsv"),
                    REPO.resolve("samples-field/baseline.tsv")),
            new Folder("corpus-public", REPO.resolve("corpus-public"), List.of(), null,
                    REPO.resolve("corpus-public/baseline.tsv")),
            new Folder("corpus-constructs", REPO.resolve("corpus-constructs"),
                    List.of(REPO.resolve("corpus-constructs/sql")), null,
                    REPO.resolve("corpus-constructs/baseline.tsv")));

    /** A baseline entry: an accepted finding, or every finding of one rule when "*". */
    private record Accepted(String ruleId, String at, String reason) {
    }

    /** What one folder measured: hits and expected rows per rule, keyed "file:line", and the accepted rows. */
    private record Measured(Folder folder, Map<String, Set<String>> hits,
            Map<String, Set<String>> expected, List<Accepted> baseline) {

        Set<String> hits(String ruleId) {
            return hits.getOrDefault(ruleId, Set.of());
        }

        Set<String> expected(String ruleId) {
            return expected.getOrDefault(ruleId, Set.of());
        }

        long matched(String ruleId) {
            return expected(ruleId).stream().filter(hits(ruleId)::contains).count();
        }

        boolean isAccepted(String ruleId, String place) {
            return baseline.stream().anyMatch(entry -> entry.ruleId().equals(ruleId)
                    && ("*".equals(entry.at()) || entry.at().equals(place)));
        }

        boolean acceptedWholesale(String ruleId) {
            return baseline.stream()
                    .anyMatch(entry -> entry.ruleId().equals(ruleId) && "*".equals(entry.at()));
        }

        /** The hits that are neither expected nor accepted. */
        Set<String> unexplained(String ruleId) {
            return hits(ruleId).stream()
                    .filter(place -> !expected(ruleId).contains(place) && !isAccepted(ruleId, place))
                    .collect(Collectors.toCollection(TreeSet::new));
        }

        long acceptedCount(String ruleId) {
            return hits(ruleId).stream()
                    .filter(place -> !expected(ruleId).contains(place) && isAccepted(ruleId, place))
                    .count();
        }

        String reasonAt(String ruleId, String place) {
            return baseline.stream()
                    .filter(e -> e.ruleId().equals(ruleId)
                            && ("*".equals(e.at()) || e.at().equals(place)))
                    .map(Accepted::reason).findFirst().orElse("NOT BASELINED");
        }
    }

    private static Map<String, Measured> measured;

    @BeforeAll
    static void measure() throws IOException {
        measured = new LinkedHashMap<>();
        for (Folder folder : FOLDERS) {
            measured.put(folder.name(), new Measured(folder, hits(folder),
                    folder.expected() == null ? Map.of() : expectedFindings(folder.expected()),
                    folder.baseline() == null ? List.of() : baseline(folder.baseline())));
        }
        writeReport();
    }

    @Test
    void everyHitOnABaselinedFolderIsExpectedOrAccepted() {
        Set<String> unexplained = new TreeSet<>();
        for (Measured m : measured.values()) {
            if (m.folder().baseline() == null) {
                continue;
            }
            for (String ruleId : m.hits().keySet()) {
                for (String place : m.unexplained(ruleId)) {
                    unexplained.add(m.folder().name() + " " + ruleId + " " + place);
                }
            }
        }
        assertEquals(Set.of(), unexplained,
                "a finding that is not a listed defect is a false positive: fix it, or record it in "
                        + "the folder's baseline.tsv with a reason");
    }

    @Test
    void everyBaselineEntryStillFires() {
        Set<String> stale = new TreeSet<>();
        for (Measured m : measured.values()) {
            for (Accepted entry : m.baseline()) {
                Set<String> places = m.hits(entry.ruleId());
                boolean fires = "*".equals(entry.at()) ? !places.isEmpty() : places.contains(entry.at());
                if (!fires) {
                    stale.add(m.folder().name() + " " + entry.ruleId() + " " + entry.at());
                }
            }
        }
        assertEquals(Set.of(), stale, "these baseline entries no longer fire: delete them from "
                + "the folder's baseline.tsv");
    }

    @Test
    void everyEnabledRuleHasAPositiveFixture() {
        String testSources = readRuleTestSources();
        Set<String> withExpectedRow = measured.values().stream()
                .flatMap(m -> m.expected().keySet().stream()).collect(Collectors.toSet());
        List<String> uncovered = BuiltinRules.all().stream()
                .filter(rule -> rule.meta().defaultEnabled())
                .filter(rule -> !withExpectedRow.contains(rule.meta().id())
                        && !testSources.contains("new " + rule.getClass().getSimpleName() + "("))
                .map(rule -> rule.meta().id())
                .toList();
        assertEquals(List.of(), uncovered,
                "a rule that is on by default needs a positive fixture: a row in an "
                        + "expected-findings.tsv, or a test under " + RULES_TESTS
                        + " that builds the rule and evaluates it");
    }

    /** Guards the folders the whole measurement rests on. */
    @Test
    void everyAssetFolderWasAnalysed() {
        for (Folder folder : FOLDERS) {
            assertTrue(Files.isDirectory(folder.dir()), folder.dir() + " must exist");
        }
    }

    // ---- measurement ----

    /** Every rule of the build, forced on, so a default-off rule is measured too. */
    private static RuleSet everyRuleEnabled() {
        Map<String, RulesFile.RuleOverride> on = new LinkedHashMap<>();
        for (Rule rule : BuiltinRules.all()) {
            on.put(rule.meta().id(), new RulesFile.RuleOverride(true, null));
        }
        return RuleSet.load(new RulesFile(on, List.of(), List.of()));
    }

    /** lint plus sql-lint over one asset folder, keyed rule id to "file:line". */
    private static Map<String, Set<String>> hits(Folder folder) {
        RuleSet ruleSet = everyRuleEnabled();
        LintRunner.Result lint = LintRunner.run(
                new LintRunner.Options(folder.dir(), folder.copybooks(), Map.of(), ruleSet));
        List<Finding> findings = new ArrayList<>(lint.findings());
        findings.addAll(lint.sqlFindings());
        Map<String, Set<String>> byRule = new TreeMap<>();
        for (Finding finding : findings) {
            // Decode and parse failures are folded in as findings but are not rule hits.
            if (!finding.ruleId().matches("[RS]\\d+")) {
                continue;
            }
            byRule.computeIfAbsent(finding.ruleId(), id -> new TreeSet<>())
                    .add(finding.location().file() + ":" + finding.location().line());
        }
        return byRule;
    }

    private static Map<String, Set<String>> expectedFindings(Path file) throws IOException {
        Map<String, Set<String>> byRule = new TreeMap<>();
        for (String line : Files.readAllLines(file, StandardCharsets.UTF_8)) {
            if (line.isBlank() || line.startsWith("no\t")) {
                continue;
            }
            String[] c = line.split("\t");
            byRule.computeIfAbsent(c[3], id -> new TreeSet<>()).add(c[1] + ":" + c[2]);
        }
        return byRule;
    }

    private static List<Accepted> baseline(Path file) throws IOException {
        List<Accepted> entries = new ArrayList<>();
        for (String line : Files.readAllLines(file, StandardCharsets.UTF_8)) {
            if (line.isBlank() || line.startsWith("#") || line.startsWith("ruleId\t")) {
                continue;
            }
            String[] c = line.split("\t", 3);
            entries.add(new Accepted(c[0].strip(), c[1].strip(), c[2].strip()));
        }
        return entries;
    }

    private static String readRuleTestSources() {
        try (Stream<Path> files = Files.walk(RULES_TESTS)) {
            return files.filter(path -> path.toString().endsWith("Test.java"))
                    .map(RuleEvaluationReportTest::readString)
                    .collect(Collectors.joining("\n"));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static String readString(Path path) {
        try {
            return Files.readString(path, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    // ---- report ----

    /**
     * Rewrites the measured section of {@code corpus/rule-hits.md} in place. The prose around the
     * markers — the verdict on each rule and why — is written by hand and left alone.
     */
    private static void writeReport() throws IOException {
        String existing = Files.readString(REPORT, StandardCharsets.UTF_8);
        int begin = existing.indexOf(BEGIN);
        int end = existing.indexOf(END);
        if (begin < 0 || end < 0) {
            throw new IllegalStateException(REPORT + " must carry the generated-section markers");
        }
        String rewritten = existing.substring(0, begin + BEGIN.length()) + "\n\n" + table() + "\n"
                + existing.substring(end);
        if (!rewritten.equals(existing)) {
            Files.writeString(REPORT, rewritten, StandardCharsets.UTF_8);
        }
    }

    private static String table() {
        Measured samples = measured.get("samples");
        Measured field = measured.get("samples-field");
        Measured corpus = measured.get("corpus");
        Measured pub = measured.get("corpus-public");
        Measured constructs = measured.get("corpus-constructs");
        StringBuilder out = new StringBuilder();
        out.append("| rule | samples hits | matched expected | unmatched samples")
                .append(" | field hits | matched field expected | field accepted | corpus hits")
                .append(" | public hits | constructs hits")
                .append(" | baseline verdict |\n|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|---|\n");
        for (Rule rule : BuiltinRules.all().stream()
                .sorted(Comparator.comparing(r -> r.meta().id())).toList()) {
            String id = rule.meta().id();
            long accepted = corpus.acceptedCount(id) + field.acceptedCount(id)
                    + pub.acceptedCount(id) + constructs.acceptedCount(id);
            out.append("| ").append(id).append(rule.meta().defaultEnabled() ? "" : " (off)")
                    .append(" | ").append(samples.hits(id).size())
                    .append(" | ").append(samples.matched(id)).append('/').append(samples.expected(id).size())
                    .append(" | ").append(samples.hits(id).size() - samples.matched(id))
                    .append(" | ").append(field.hits(id).size())
                    .append(" | ").append(field.matched(id)).append('/').append(field.expected(id).size())
                    .append(" | ").append(field.acceptedCount(id))
                    .append(" | ").append(corpus.hits(id).size())
                    .append(" | ").append(pub.hits(id).size())
                    .append(" | ").append(constructs.hits(id).size())
                    .append(" | ").append(accepted == 0 ? "no false positive"
                            : accepted + " accepted, see below")
                    .append(" |\n");
        }
        out.append("\nAccepted findings and why each is accepted. A rule a baseline accepts"
                        + " wholesale gets one row listing every place it fired:\n\n")
                .append("| rule | folder | where | why it is accepted |\n|---|---|---|---|\n");
        for (Measured m : List.of(corpus, field, pub, constructs)) {
            m.hits().forEach((id, places) -> {
                if (m.acceptedWholesale(id)) {
                    out.append("| ").append(id).append(" | ").append(m.folder().name())
                            .append(" | ").append(String.join(", ", places))
                            .append(" | ").append(m.reasonAt(id, places.iterator().next()))
                            .append(" |\n");
                    return;
                }
                places.stream().filter(place -> !m.expected(id).contains(place))
                        .forEach(place -> out.append("| ").append(id)
                                .append(" | ").append(m.folder().name())
                                .append(" | ").append(place)
                                .append(" | ").append(m.reasonAt(id, place))
                                .append(" |\n"));
            });
        }
        return out.toString();
    }
}
