package jp.cobolinsight.app.rules;

import jp.cobolinsight.app.cli.LintRunner;
import jp.cobolinsight.app.cli.SqlAdviseRunner;
import jp.cobolinsight.core.finding.Finding;
import jp.cobolinsight.core.rule.Rule;
import jp.cobolinsight.rules.BuiltinRules;
import jp.cobolinsight.rules.RuleSet;
import jp.cobolinsight.rules.RulesFile;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The measurement harness behind {@code corpus/rule-hits.md}.
 *
 * <p>It runs every built-in rule — the {@code rules.json} of the machine is ignored and every rule
 * is forced on, so a rule that ships disabled is still measured — over {@code samples/}, whose
 * intentional defects are listed in {@code samples/expected-findings.tsv}, and over {@code corpus/},
 * which is deliberately defect-free. A finding on the corpus is therefore a false positive by
 * construction, and every one of them has to be written down in {@code corpus/baseline.tsv} with a
 * reason. The test fails when a corpus hit is missing from the baseline, and when a baseline entry
 * no longer fires: noise then arrives as a reviewable diff rather than as a silent drift.
 *
 * <p>It also gates coverage: a rule that is on by default must have at least one positive fixture,
 * either a row in {@code expected-findings.tsv} or its id in a test under the {@code rules} module.
 */
class RuleEvaluationReportTest {

    private static final Path REPO = Path.of("..", "..", "..").toAbsolutePath().normalize();
    private static final Path SAMPLES = REPO.resolve("samples");
    private static final Path CORPUS = REPO.resolve("corpus");
    private static final Path RULES_TESTS =
            REPO.resolve("src/engine/rules/src/test/java/jp/cobolinsight/rules");
    private static final Path REPORT = CORPUS.resolve("rule-hits.md");
    private static final Path BASELINE = CORPUS.resolve("baseline.tsv");

    private static final String BEGIN = "<!-- generated by RuleEvaluationReportTest: begin -->";
    private static final String END = "<!-- generated by RuleEvaluationReportTest: end -->";

    /** A baseline entry: an accepted corpus finding, or every finding of one rule when "*". */
    private record Accepted(String ruleId, String at, String reason) {

        String key() {
            return ruleId + "\t" + at;
        }
    }

    /** Findings of one rule, keyed "file:line", over one asset folder. */
    private static Map<String, Set<String>> samplesHits;
    private static Map<String, Set<String>> corpusHits;
    private static Map<String, Set<String>> expected;
    private static List<Accepted> baseline;

    @BeforeAll
    static void measure() throws IOException {
        samplesHits = hits(SAMPLES, SAMPLES.resolve("copybook"));
        corpusHits = hits(CORPUS, CORPUS);
        expected = expectedFindings();
        baseline = baseline();
        writeReport();
    }

    @Test
    void everyCorpusHitIsAccountedForInTheBaseline() {
        Set<String> unexplained = new TreeSet<>();
        corpusHits.forEach((ruleId, places) -> {
            for (String place : places) {
                if (!isAccepted(ruleId, place)) {
                    unexplained.add(ruleId + " " + place);
                }
            }
        });
        assertEquals(Set.of(), unexplained,
                "a finding on the defect-free corpus is a false positive: fix it, or record it in "
                        + BASELINE + " with a reason");
    }

    @Test
    void everyBaselineEntryStillFires() {
        Set<String> stale = new TreeSet<>();
        for (Accepted entry : baseline) {
            Set<String> places = corpusHits.getOrDefault(entry.ruleId(), Set.of());
            boolean fires = "*".equals(entry.at()) ? !places.isEmpty() : places.contains(entry.at());
            if (!fires) {
                stale.add(entry.ruleId() + " " + entry.at());
            }
        }
        assertEquals(Set.of(), stale, "these baseline entries no longer fire: delete them from "
                + BASELINE);
    }

    @Test
    void everyEnabledRuleHasAPositiveFixture() {
        String testSources = readRuleTestSources();
        List<String> uncovered = BuiltinRules.all().stream()
                .filter(rule -> rule.meta().defaultEnabled())
                .filter(rule -> !expected.containsKey(rule.meta().id())
                        && !testSources.contains("new " + rule.getClass().getSimpleName() + "("))
                .map(rule -> rule.meta().id())
                .toList();
        assertEquals(List.of(), uncovered,
                "a rule that is on by default needs a positive fixture: a row in "
                        + "samples/expected-findings.tsv, or a test under " + RULES_TESTS
                        + " that builds the rule and evaluates it");
    }

    // ---- measurement ----

    /** Every rule of the build, forced on, so a default-off rule is measured too. */
    private static RuleSet everyRuleEnabled() {
        Map<String, RulesFile.RuleOverride> on = new LinkedHashMap<>();
        for (Rule rule : BuiltinRules.all()) {
            on.put(rule.meta().id(), new RulesFile.RuleOverride(true, null));
        }
        return RuleSet.load(new RulesFile(on, List.of(), List.of()));
    }

    /** lint plus sql-lint over one asset folder, keyed rule id to "file:line". */
    private static Map<String, Set<String>> hits(Path dir, Path copybooks) {
        RuleSet ruleSet = everyRuleEnabled();
        List<Finding> findings = new ArrayList<>(
                LintRunner.run(new LintRunner.Options(dir, List.of(copybooks), Map.of(), ruleSet))
                        .findings());
        findings.addAll(SqlAdviseRunner.run(
                new SqlAdviseRunner.Options(dir, List.of(copybooks), Map.of(), ruleSet)).findings());
        Map<String, Set<String>> byRule = new TreeMap<>();
        for (Finding finding : findings) {
            // Decode and parse failures are folded in as findings but are not rule hits.
            if (!finding.ruleId().matches("[RS]\\d+")) {
                continue;
            }
            byRule.computeIfAbsent(finding.ruleId(), id -> new TreeSet<>())
                    .add(finding.location().file() + ":" + finding.location().line());
        }
        return byRule;
    }

    private static Map<String, Set<String>> expectedFindings() throws IOException {
        Map<String, Set<String>> byRule = new TreeMap<>();
        for (String line : Files.readAllLines(SAMPLES.resolve("expected-findings.tsv"),
                StandardCharsets.UTF_8).subList(1, 19)) {
            String[] c = line.split("\t");
            byRule.computeIfAbsent(c[3], id -> new TreeSet<>()).add(c[1] + ":" + c[2]);
        }
        return byRule;
    }

    private static List<Accepted> baseline() throws IOException {
        List<Accepted> entries = new ArrayList<>();
        for (String line : Files.readAllLines(BASELINE, StandardCharsets.UTF_8)) {
            if (line.isBlank() || line.startsWith("#") || line.startsWith("ruleId\t")) {
                continue;
            }
            String[] c = line.split("\t", 3);
            entries.add(new Accepted(c[0].strip(), c[1].strip(), c[2].strip()));
        }
        return entries;
    }

    private static boolean isAccepted(String ruleId, String place) {
        return baseline.stream().anyMatch(entry -> entry.ruleId().equals(ruleId)
                && ("*".equals(entry.at()) || entry.at().equals(place)));
    }

    private static String readRuleTestSources() {
        try (Stream<Path> files = Files.walk(RULES_TESTS)) {
            return files.filter(path -> path.toString().endsWith("Test.java"))
                    .map(RuleEvaluationReportTest::readString)
                    .collect(Collectors.joining("\n"));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static String readString(Path path) {
        try {
            return Files.readString(path, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    // ---- report ----

    /**
     * Rewrites the measured section of {@code corpus/rule-hits.md} in place. The prose around the
     * markers — the verdict on each rule and why — is written by hand and left alone.
     */
    private static void writeReport() throws IOException {
        String existing = Files.readString(REPORT, StandardCharsets.UTF_8);
        int begin = existing.indexOf(BEGIN);
        int end = existing.indexOf(END);
        if (begin < 0 || end < 0) {
            throw new IllegalStateException(REPORT + " must carry the generated-section markers");
        }
        String rewritten = existing.substring(0, begin + BEGIN.length()) + "\n\n" + table() + "\n"
                + existing.substring(end);
        if (!rewritten.equals(existing)) {
            Files.writeString(REPORT, rewritten, StandardCharsets.UTF_8);
        }
    }

    private static String table() {
        StringBuilder out = new StringBuilder();
        out.append("| rule | samples hits | matched expected | unmatched samples | corpus hits |")
                .append(" baseline verdict |\n|---|--:|--:|--:|--:|---|\n");
        for (Rule rule : BuiltinRules.all().stream()
                .sorted(java.util.Comparator.comparing(r -> r.meta().id())).toList()) {
            String id = rule.meta().id();
            Set<String> found = samplesHits.getOrDefault(id, Set.of());
            Set<String> wanted = expected.getOrDefault(id, Set.of());
            long matched = wanted.stream().filter(found::contains).count();
            int corpus = corpusHits.getOrDefault(id, Set.of()).size();
            out.append("| ").append(id).append(rule.meta().defaultEnabled() ? "" : " (off)")
                    .append(" | ").append(found.size())
                    .append(" | ").append(matched).append('/').append(wanted.size())
                    .append(" | ").append(found.size() - matched)
                    .append(" | ").append(corpus)
                    .append(" | ").append(corpus == 0 ? "no false positive"
                            : baselinedCount(id) + " accepted, see below")
                    .append(" |\n");
        }
        out.append("\nCorpus findings and why each is accepted. A rule the baseline accepts"
                        + " wholesale gets one row listing every place it fired:\n\n")
                .append("| rule | where | why it is accepted |\n|---|---|---|\n");
        corpusHits.forEach((id, places) -> {
            if (acceptedWholesale(id)) {
                out.append("| ").append(id).append(" | ").append(String.join(", ", places))
                        .append(" | ").append(reasonAt(id, places.iterator().next()))
                        .append(" |\n");
                return;
            }
            places.forEach(place -> out.append("| ").append(id)
                    .append(" | ").append(place).append(" | ").append(reasonAt(id, place))
                    .append(" |\n"));
        });
        return out.toString();
    }

    private static boolean acceptedWholesale(String ruleId) {
        return baseline.stream()
                .anyMatch(entry -> entry.ruleId().equals(ruleId) && "*".equals(entry.at()));
    }

    private static long baselinedCount(String ruleId) {
        return corpusHits.getOrDefault(ruleId, Set.of()).stream()
                .filter(place -> isAccepted(ruleId, place)).count();
    }

    private static String reasonAt(String ruleId, String place) {
        return baseline.stream()
                .filter(e -> e.ruleId().equals(ruleId)
                        && ("*".equals(e.at()) || e.at().equals(place)))
                .map(Accepted::reason).findFirst().orElse("NOT BASELINED");
    }

    /** Guards the two folders the whole measurement rests on. */
    @Test
    void bothAssetFoldersWereAnalysed() {
        assertTrue(Files.isDirectory(CORPUS), CORPUS + " must exist");
        assertTrue(Files.isDirectory(SAMPLES), SAMPLES + " must exist");
    }
}
