/**
 * Every user-visible string in the renderer. The product is Japanese, so the values are Japanese and
 * the keys are English; keeping them all here lets a later wording pass edit one file.
 *
 * Rule names, categories and prose are deliberately absent: the engine is their only source and the
 * screens render what `rules --json` returns.
 */
export const text = {
  app: {
    name: "COBOL Insight",
    run: "解析を実行",
    cancel: "中止",
    running: "解析中",
  },

  activity: {
    explorer: "資産",
    search: "検索",
    rules: "ルール",
    problems: "指摘",
    label: "画面の切り替え",
  },

  sideBar: {
    explorerTitle: "資産エクスプローラー",
    searchTitle: "検索",
    rulesTitle: "ルール",
    problemsTitle: "指摘",
    label: "サイドバー",
    resize: "サイドバーの幅",
  },

  editor: {
    tabs: "開いているファイル",
    close: "閉じる",
    unsaved: "未保存の変更",
    empty: "ファイルを開いていません",
  },

  panel: {
    label: "パネル",
    problems: "指摘",
    output: "出力",
    resize: "パネルの高さ",
    close: "パネルを閉じる",
  },

  status: {
    label: "ステータス",
    noFolder: "資産フォルダ未選択",
    assets: "資産",
    findings: "指摘",
    sqlFindings: "SQL指摘",
    stage: (stage: number, total: number): string => `第 ${stage} / ${total} 段`,
    unit: "件",
  },

  welcome: {
    title: "COBOL Insight",
    lead: "メインフレーム資産のフォルダを選ぶと、走査・検出・SQL検出を順に実行します。",
    selectFolder: "資産フォルダを選ぶ",
    recent: "前回のフォルダ",
    shortcutHint: "コマンドパレットは Ctrl+Shift+P で開きます。",
  },

  explorer: {
    selectFolder: "資産フォルダを選ぶ",
    changeFolder: "フォルダを変更",
    search: "名前で絞り込む",
    searchLabel: "資産の名前で絞り込む",
    typeLabel: "種別で絞り込む",
    tree: "資産ツリー",
    empty: "資産フォルダを選ぶと、ここに資産が並びます。",
    loading: "走査しています…",
    noMatch: "絞り込みに一致する資産がありません。",
    error: "資産一覧を読めませんでした。",
    codepageUnknown: "文字コード不明",
    findingCount: (count: number): string => `指摘 ${count} 件`,
  },

  assetType: {
    all: "すべて",
    cobol: "COBOL",
    copybook: "コピー句",
    jcl: "JCL",
    bms: "BMS",
    other: "その他",
  },

  severity: {
    high: "高",
    medium: "中",
    low: "低",
    warning: "注意",
  },

  problems: {
    title: "指摘",
    empty: "解析を実行すると、ここに指摘が並びます。",
    loading: "検出しています…",
    noMatch: "絞り込みに一致する指摘がありません。",
    clean: "指摘はありません。",
    error: "指摘を読めませんでした。",
    search: "内容で絞り込む",
    searchLabel: "指摘の内容で絞り込む",
    allRules: "ルール: すべて",
    allFiles: "資産: すべて",
    allSources: "出所: すべて",
    thresholdNote: "重大度しきい値より低い指摘は表に出していません。",
    columnSeverity: "重大度",
    columnRule: "ルール",
    columnMessage: "内容",
    columnFile: "資産",
    columnLine: "行",
    sortLabel: "並び順",
    sortSeverity: "重大度順",
    sortFile: "資産順",
    sortRule: "ルール順",
  },

  source: {
    lint: "コード",
    sql: "SQL",
    save: "保存時の検証",
  },

  output: {
    title: "出力",
    empty: "解析を実行すると、ここに実行ログが出ます。",
    clear: "ログを消す",
  },

  sourceView: {
    loading: "本文を読み込んでいます…",
    error: "本文を表示できませんでした。",
    codepage: "文字コード",
    detected: "自動判別",
    lines: (count: number): string => `${count} 行`,
  },

  run: {
    scan: "走査",
    lint: "指摘の検出",
    sqlLint: "SQL指摘の検出",
    started: "解析を開始しました。",
    cancelled: "解析を中止しました（完了した分の結果は残ります）。",
    stageStarted: (stage: string): string => `${stage}を開始しました。`,
    stageDone: (stage: string, count: number): string => `${stage}を終えました（${count} 件）。`,
    stageFailed: (stage: string, reason: string): string => `${stage}に失敗しました。${reason}`,
    scanDone: (count: number): string => `走査を終えました（資産 ${count} 件）。`,
    noFolder: "先に資産フォルダを選んでください。",
  },

  palette: {
    label: "コマンドパレット",
    placeholder: "コマンドを入力",
    noMatch: "一致するコマンドがありません。",
  },

  command: {
    categoryFile: "ファイル",
    categoryView: "表示",
    categoryRun: "実行",
    selectFolder: "資産フォルダを選ぶ",
    run: "解析を実行する",
    cancel: "解析を中止する",
    toggleSideBar: "サイドバーの表示を切り替える",
    togglePanel: "パネルの表示を切り替える",
    showExplorer: "資産エクスプローラーを開く",
    showSearch: "検索を開く",
    showRules: "ルールを開く",
    showProblems: "指摘を開く",
    showOutput: "出力を開く",
    showSettings: "設定を開く",
    toggleRule: "このルールの有効・無効を切り替える",
    validateCustomRules: "利用者定義ルールを検証する",
    saveCustomRules: "利用者定義ルールを保存する",
    categoryRules: "ルール",
    closeTab: "タブを閉じる",
    nextTab: "次のタブへ",
    previousTab: "前のタブへ",
  },

  modal: {
    confirmDiscardTitle: "保存していない変更があります",
    confirmDiscardBody: "閉じると、この資産への編集は失われます。",
    discard: "破棄して閉じる",
    keep: "編集を続ける",
    close: "閉じる",
  },

  toast: {
    close: "通知を閉じる",
  },

  placeholder: {
    notImplemented: "この画面はまだありません。",
  },

  rules: {
    search: "ルールを絞り込む",
    searchLabel: "ルールの ID・名前・概要で絞り込む",
    empty: "ルールを読み込んでいます…",
    noMatch: "絞り込みに一致するルールがありません。",
    enableAll: "表示中をすべて有効",
    disableAll: "表示中をすべて無効",
    enableGroup: "この分類をすべて有効",
    disableGroup: "この分類をすべて無効",
    enabledLabel: (id: string): string => `${id} を有効にする`,
    builtin: "組み込み",
    user: "利用者定義",
    hasFix: "修正案あり",
    openCustom: "利用者定義ルールを編集",
    ruleErrors: "ルール設定に問題があります。",
    severityLabel: (id: string): string => `${id} の重大度`,
    severityDefault: "既定に戻す",
    detailSummary: "検出する内容",
    detailRationale: "なぜ問題か",
    detailDetection: "検出の仕方",
    detailRemedy: "直し方",
    detailBad: "指摘される例",
    detailGood: "直した例",
    detailCommands: "実行するコマンド",
    detailTargets: "対象の資産",
    detailUnknown: "このルールはカタログにありません。",
  },

  customRules: {
    title: "利用者定義ルール",
    paneForm: "フォーム",
    paneRaw: "直接編集",
    paneLabel: "編集の仕方",
    rawLabel: "custom 配列の JSON",
    rawInvalid: (detail: string): string => `JSON として読めません。${detail}`,
    rawNotArray: "custom はルール定義の配列で書きます。",
    rawBlocked: "JSON を直せるまでフォームへは戻れません。",
    add: "ルールを足す",
    remove: "このルールを消す",
    validate: "検証する",
    save: "保存する",
    empty: "利用者定義ルールはまだありません。",
    validationOk: "engine はこの内容を受け付けました。",
    validationFailed: "engine がこの内容を受け付けませんでした。",
    dirty: "未保存の変更があります。",
    fieldId: "ID",
    fieldName: "名前",
    fieldCategory: "分類",
    fieldSummary: "概要",
    fieldSeverity: "重大度",
    fieldCommands: "実行するコマンド",
    fieldTargets: "対象の資産",
    fieldMessage: "指摘の文言",
    fieldRationale: "なぜ問題か",
    fieldRemedy: "直し方",
    fieldMatchKind: "検出の仕方",
    fieldRegex: "正規表現",
    fieldIgnoreCase: "大文字小文字を区別しない",
    fieldArea: "走査する範囲",
    fieldExcludeRegex: "除外する正規表現",
    fieldVerb: "対象の動詞",
    fieldMissingClause: "欠けていると指摘する句",
    fieldInParagraph: "対象の段落名（正規表現）",
    fieldAfterVerb: "起点の動詞",
    fieldAfterTextRegex: "起点の文の正規表現",
    fieldDataItem: "検査するデータ項目",
    fieldScope: "追う範囲",
    fieldOnEveryPath: "すべての経路で検査を求める",
    listHint: "読点または改行で区切ります。",
    messageHint: "${match} と書くと、一致した文字列に置き換わります。",
    matchKind: {
      line: "行の正規表現",
      statement: "文と句",
      "checked-after": "文の後の検査",
    },
    area: {
      programArea: "本体（8〜72桁・注記行を除く）",
      wholeLine: "行全体",
    },
    scope: {
      untilNextMatchingStatement: "同じ動詞の次の文まで",
      untilParagraphEnd: "段落の終わりまで",
      untilProgramEnd: "プログラムの終わりまで",
    },
    problem: {
      idFormat: "ID は U で始め、英数字・ハイフン・下線を1〜15文字続けます。",
      idDuplicate: "この ID は他のルールと重なっています。",
      nameRequired: "名前を書きます。",
      messageRequired: "指摘の文言を書きます。",
      regexRequired: "正規表現を書きます。",
      verbRequired: "対象の動詞を書きます。",
      afterVerbRequired: "起点の動詞を書きます。",
      dataItemRequired: "検査するデータ項目を書きます。",
    },
  },

  settings: {
    title: "設定",
    encoding: "既定の文字コード",
    encodingAuto: "自動判別",
    encodingNote: "資産ごとの指定が無いときに engine へ渡します。",
    copybookPaths: "コピー句の探索パス",
    copybookAdd: "パスを足す",
    copybookRemove: "このパスを消す",
    copybookPlaceholder: "C:\\assets\\copybook",
    copybookMissing: "このフォルダは見つかりません。",
    threshold: "指摘の重大度しきい値",
    thresholdNote: "これより低い重大度の指摘は指摘一覧に出しません。",
    fixOutDir: "修正案の出力先",
    fixOutDirNote: "空にすると engine の既定の場所へ書き出します。原本は書き換えません。",
    save: "保存する",
    saved: "保存しました。",
    dirty: "未保存の変更があります。",
  },

  import: {
    open: "端末から取り込む",
    title: "端末取込",
    paste: "端末から複写した本文",
    pastePlaceholder: "端末エミュレータの画面で範囲を選んで複写し、ここへ貼り付けます。",
    kind: "資産の種別",
    copybookNote: "コピー句には、COPY 文から引けるよう拡張子 .cpy を補います。",
    destDir: "保存先",
    destDirPlaceholder: "資産フォルダの直下",
    destDirNote: "資産フォルダからの相対パス。",
    fileName: "ファイル名",
    fileNamePlaceholder: "SYK001.cbl",
    fileNameInvalid: 'パス区切りと記号 \\ / : * ? " < > | は使えません。',
    destination: (relPath: string): string => `保存先: ${relPath}`,
    columns: "取り込む桁",
    columnFrom: "開始桁",
    columnTo: "終了桁",
    columnsNote:
      "端末の表示桁で数えます（1起点・両端を含む）。行番号欄ごと複写したときは、本文が始まる桁を開始桁にします。",
    columnsInvalid: "終了桁は開始桁以上にします。",
    preview: "切り出した本文",
    previewEmpty: "本文を貼り付けると、ここに切り出した結果が出ます。",
    lineCount: (count: number): string => `${count} 行`,
    save: "保存",
    saving: "保存しています…",
    cancel: "やめる",
    encodingNote: "保存は UTF-8 で行います。",
    exists: (relPath: string): string =>
      `${relPath} は既にあります。上書きすると元の内容は失われます。`,
    overwrite: "上書きする",
    saved: (relPath: string, count: number): string =>
      `${relPath} を書き出しました（${count} 行）。再解析すると一覧に出ます。`,
    noFolder: "先に資産フォルダを選んでください。",
  },
} as const;
