      *----------------------------------------------------------------
      * CSH501 -- host-variable-only copybook (no DECLARE TABLE).
      *   Pulled in with EXEC SQL INCLUDE by CSQ503. Carries plain
      *   WORKING-STORAGE host variables and one indicator, hand
      *   written to match CSDB.CSQKOZA rather than generated by
      *   DCLGEN.
      *----------------------------------------------------------------
       01  WS-CSH-HOST-VARS.
           05  WS-CSH-KOZA-NO         PIC X(10).
           05  WS-CSH-KOKYAKU-NO      PIC X(8).
           05  WS-CSH-ZANDAKA         PIC S9(11) USAGE COMP-3.
           05  WS-CSH-KOSHIN-YMD      PIC X(8).
           05  WS-CSH-KOSHIN-YMD-IND  PIC S9(4)  USAGE COMP.
