      *----------------------------------------------------------------*
      * PROGRAM-ID : CSQ201
      * Constructs : EXEC SQL INCLUDE SQLCA / SQLDA; EXEC SQL INCLUDE
      *   CSD201 (a DCLGEN member); EXEC SQL DECLARE TABLE written
      *   inline (not from a DCLGEN); BEGIN DECLARE SECTION / END
      *   DECLARE SECTION around plain host variables; WHENEVER
      *   SQLERROR GO TO; WHENEVER SQLWARNING CONTINUE; WHENEVER NOT
      *   FOUND GO TO scoped to one statement, cancelled right after
      *   by WHENEVER NOT FOUND CONTINUE; a cursor declared WITHOUT
      *   HOLD, FOR READ ONLY, opened, fetched in a loop until
      *   SQLCODE = 100, and closed.
      *----------------------------------------------------------------*
       IDENTIFICATION DIVISION.
       PROGRAM-ID.    CSQ201.
       AUTHOR.        CSQ-CONSTRUCTS-DEV.

       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-370.
       OBJECT-COMPUTER. IBM-370.

       DATA DIVISION.
       WORKING-STORAGE SECTION.

           EXEC SQL INCLUDE SQLCA END-EXEC.
           EXEC SQL INCLUDE SQLDA END-EXEC.
           EXEC SQL INCLUDE CSD201 END-EXEC.

      * A lookup table declared inline, not generated by DCLGEN.
           EXEC SQL
               DECLARE CSQDB.BUMON TABLE
               ( BUMON_CD                CHAR(4) NOT NULL,
                 BUMON_MEI               CHAR(20) NOT NULL,
                 BUMON_KANRISHA          CHAR(8)
               )
           END-EXEC.

           EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01  WS-BUMON-CD                PIC X(04).
       01  WS-BUMON-MEI               PIC X(20).
           EXEC SQL END DECLARE SECTION END-EXEC.

       01  WS-PARM-AREA.
           05  WS-PARM-BUMON-CD       PIC X(04).
           05  FILLER                 PIC X(76).

       01  WS-COUNTERS.
           05  WS-READ-CNT            PIC 9(07) VALUE ZERO.

       PROCEDURE DIVISION.

       0000-MAIN.
           EXEC SQL WHENEVER SQLERROR GO TO 9000-SQL-ERROR END-EXEC
           EXEC SQL WHENEVER SQLWARNING CONTINUE END-EXEC
           PERFORM 1000-INIT
           PERFORM 2000-BUMON-LOOKUP
           PERFORM 3000-SHOHIN-LIST
           PERFORM 8000-END
           STOP RUN.

       1000-INIT.
           ACCEPT WS-PARM-AREA
           MOVE WS-PARM-BUMON-CD TO WS-BUMON-CD.

      *----- 該当行なし（+100）をこの 1 文だけ GO TO で捕捉します -----
       2000-BUMON-LOOKUP.
           EXEC SQL
               WHENEVER NOT FOUND GO TO 9100-BUMON-NOT-FOUND
           END-EXEC
           EXEC SQL
               SELECT BUMON_MEI
                 INTO :WS-BUMON-MEI
                 FROM CSQDB.BUMON
                WHERE BUMON_CD = :WS-BUMON-CD
           END-EXEC
           EXEC SQL WHENEVER NOT FOUND CONTINUE END-EXEC
           DISPLAY 'CSQ201 部門名 = ' WS-BUMON-MEI.

      *----- 取扱区分が '1' の商品を一覧表示します -----
       3000-SHOHIN-LIST.
           EXEC SQL
               DECLARE CSR-LIST CURSOR WITHOUT HOLD FOR
                   SELECT SHOHIN_CD, SHOHIN_MEI, TANKA
                     FROM CSQDB.SHOHIN
                    WHERE TORIATSUKAI_KBN = '1'
                    FOR READ ONLY
           END-EXEC
           EXEC SQL OPEN CSR-LIST END-EXEC
           PERFORM 3100-FETCH-LOOP UNTIL SQLCODE NOT = 0
           EXEC SQL CLOSE CSR-LIST END-EXEC.

       3100-FETCH-LOOP.
           EXEC SQL
               FETCH CSR-LIST
                INTO :SHOHIN-CD, :SHOHIN-MEI, :TANKA
           END-EXEC
           EVALUATE SQLCODE
               WHEN 0
                   ADD 1 TO WS-READ-CNT
                   DISPLAY '  ' SHOHIN-CD ' ' SHOHIN-MEI
               WHEN 100
                   CONTINUE
               WHEN OTHER
                   PERFORM 9000-SQL-ERROR
           END-EVALUATE.

       8000-END.
           DISPLAY 'CSQ201 件数 = ' WS-READ-CNT
           MOVE ZERO TO RETURN-CODE.

       9000-SQL-ERROR.
           EXEC SQL WHENEVER SQLERROR CONTINUE END-EXEC
           DISPLAY 'CSQ201 SQL エラー SQLCODE = ' SQLCODE
           EXEC SQL CLOSE CSR-LIST END-EXEC
           MOVE 12 TO RETURN-CODE
           GOBACK.

      *----- 部門が見つからないときは処理を打ち切ります -----
       9100-BUMON-NOT-FOUND.
           DISPLAY 'CSQ201 指定した部門コードがありません。'
           MOVE 8 TO RETURN-CODE
           GOBACK.
