package jp.cobolinsight.core.transpile;

import java.util.Objects;

/** One file generated by line-by-line translation. content is verbatim text assumed to be LF newlines, UTF-8 without a BOM. */
public record GeneratedFile(String fileName, String content) {

    public GeneratedFile {
        if (fileName == null || fileName.isBlank()) {
            throw new IllegalArgumentException("fileName must not be blank");
        }
        Objects.requireNonNull(content, "content");
    }
}
