package jp.cobolinsight.app.pipeline;

import jp.cobolinsight.core.finding.Finding;
import jp.cobolinsight.core.rule.Needs;
import jp.cobolinsight.core.semantic.CobolSemanticModel;
import jp.cobolinsight.core.semantic.EmbeddedBlock;
import jp.cobolinsight.core.semantic.EmbeddedBlockKind;
import jp.cobolinsight.core.source.AssetKind;
import jp.cobolinsight.core.sql.SqlStatementModel;
import jp.cobolinsight.rules.RuleSet;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The measurement harness behind {@code parse-report.md}: how much of an asset folder the engine
 * parses at all, as opposed to how well it judges what it parsed.
 *
 * <p>It runs the front half of {@code scan} — discover, classify, decode, parse, semantic — over
 * each corpus folder and counts what came out with a model and what did not. A JCL member with no
 * JOB card is neither a success nor a failure: {@link Parse} hands it to no parser, so it is
 * counted apart and left out of the rate. SQL is measured statement by statement, because one
 * unreadable {@code EXEC SQL} block does not cost a program its other statements. The statements of
 * an SQL script are counted apart from that rate: a script is read whole, and how much of its DDL
 * the Db2 grammar takes is a different question from how much of a program's embedded SQL it takes.
 *
 * <p>The folders measured here carry no ground truth, so nothing is compared against an expected
 * row. What is pinned is coverage: {@link #PINNED} holds the rates and the counts each folder has
 * already reached, and a change that parses less than before fails. The counts are there because a
 * rate alone cannot see a file that stops being offered to a parser at all — that file leaves the
 * numerator and the denominator together — so the floors hold what was read and the ceilings hold
 * what was lost. A folder that is not on disk yet is skipped with a log line, so this test can
 * land before its fixtures do.
 */
class ParseRateReportTest {

    private static final Path REPO = Path.of("..", "..", "..").toAbsolutePath().normalize();

    private static final String BEGIN = "<!-- generated by ParseRateReportTest: begin -->";
    private static final String END = "<!-- generated by ParseRateReportTest: end -->";

    /** Only there because {@link SourceSet.Options} takes a database path; no step here writes one. */
    private static final Path UNUSED_DATABASE =
            Path.of(System.getProperty("java.io.tmpdir"), "cobol-insight-parse-rate.db");

    /**
     * The head of the message a salvaged parameter carries. The frontend writes a parameter it
     * could not read under the same rule id as a statement it could not read at all
     * ({@code MapaJclParser.diagnostic}), and the two are different outcomes: the statement of a
     * salvaged parameter is modelled, and only its one operand stays raw text. The message is what
     * separates them, so this is the marker the count and the taxonomy both go by.
     */
    private static final String SALVAGED_PARAMETER = "JCL 文のパラメーター ";

    /**
     * What each folder has already reached, and may not fall back from. Measured on 2026-09-11
     * after the fix batches. Seven of the eight degraded SQL statements of corpus-constructs are
     * Db2 grammar limits (multi-row INSERT, G'' literals, VALUES INTO, GET DIAGNOSTICS) that a
     * statement keeps its kind and tables through; the eighth is the subscripted host variable
     * {@code :WS-BUSHO-TBL(1)} of sql/CSQ110.cbl:60, which the Db2 precompiler does not take
     * either. That one stays degraded until {@code HostVariableMangler} swallows the subscript,
     * and until then a grammar that took the other four constructs would still not reach 1.000.
     */
    private static final Map<String, Pinned> PINNED = Map.of(
            "corpus-constructs", new Pinned(1.0, 0.979, 0, 0, 2,
                    /* floors  */ 87, 76, 385, 13,
                    /* ceilings */ 11, 1, 1, 8, 2),
            "corpus-public", new Pinned(1.0, 1.0, 0, 0, 0,
                    /* floors  */ 43, 37, 28, 0,
                    /* ceilings */ 6, 2, 4, 0, 0));

    /**
     * The floors and ceilings of one folder: a rate below its floor, a count below its floor or a
     * loss above its ceiling fails.
     *
     * @param scriptDegraded the most statements of an SQL script the Db2 grammar may read only in
     *                       part. The two of corpus-constructs are the CREATE TABLE statements of
     *                       ddl/CSL501.sql that carry GENERATED ALWAYS AS IDENTITY, which the
     *                       grammar does not take (corpus-constructs/README.md).
     * @param jclFiles the fewest JCL files the walk may find, which is what catches a file that
     *                 stops being classified as JCL at all
     * @param jclWithModel the fewest of them that may produce a job model
     * @param sqlAnalysed the fewest embedded SQL statements the grammar may read in full
     * @param scriptAnalysed the fewest statements of an SQL script it may read in full
     * @param jclSkipped the most JCL files that may be read as a member rather than a job. A job
     *                   file that starts answering {@code MapaJclParser.isMember} lands here and
     *                   leaves {@link Metrics#jclRate()} at 1.000, so this is what reports it.
     * @param undecided the most files the classifier may leave of no kind, which is the other way
     *                  a file drops out of the walk without failing
     * @param cobolFailed the most COBOL files that may be lost whole. The one of corpus-constructs
     *                    is sql/CSQ308.cbl (corpus-constructs/README.md); the four of corpus-public
     *                    are the programs parse-report.md names.
     * @param jclStatementsLost the most JCL statements the parser may fail to read
     * @param jclParametersRaw the most parameters it may keep as raw text, its statement read
     */
    private record Pinned(double jclRate, double sqlRate, int jclFilesFailed, int sqlSetAside,
            int scriptDegraded, int jclFiles, int jclWithModel, int sqlAnalysed, int scriptAnalysed,
            int jclSkipped, int undecided, int cobolFailed, int jclStatementsLost,
            int jclParametersRaw) {
    }

    /** One measured folder. */
    private record Folder(String name, Path dir) {
    }

    /** One file that would not parse, or one statement the parser could not read. */
    private record Failure(String file, int line, String what, String message, String taxonomy) {
    }

    private record Metrics(String name, int jclFiles, int jclWithModel, int jclSkipped,
            int jclFailed, int jclStatementsLost, int jclParametersRaw, int jclDirectives,
            int cobolFiles, int cobolFailed, int sqlAnalysed, int sqlDegraded, int sqlSetAside,
            int scriptFiles, int scriptAnalysed, int scriptDegraded, int undecided,
            Map<AssetKind, Integer> parseFailures, List<Failure> failures) {

        /** Parsed jobs over the JCL that was offered to the parser at all. */
        double jclRate() {
            int offered = jclFiles - jclSkipped;
            return offered == 0 ? 1.0 : (double) jclWithModel / offered;
        }

        /**
         * Statements the grammar read in full, over every EXEC SQL block there was. A degraded
         * statement counts against the rate: the tool kept its kind and its tables, but it did
         * not read the statement.
         */
        double sqlRate() {
            int total = sqlAnalysed + sqlDegraded + sqlSetAside;
            return total == 0 ? 1.0 : (double) sqlAnalysed / total;
        }
    }

    private static List<Metrics> measured;

    @BeforeAll
    static void measure() throws IOException {
        measured = new ArrayList<>();
        for (Folder folder : folders()) {
            if (!Files.isDirectory(folder.dir())) {
                System.out.println("ParseRateReportTest: " + folder.dir()
                        + " is not there yet, skipped");
                continue;
            }
            measured.add(measure(folder));
        }
        writeReport();
    }

    @Test
    void everyMeasuredFolderHoldsItsPinnedRate() {
        for (Metrics m : measured) {
            Pinned pinned = PINNED.get(m.name());
            if (pinned == null) {
                // The benchmark folder holds somebody's own assets: reported, never asserted.
                continue;
            }
            assertTrue(m.jclRate() >= pinned.jclRate(), m.name() + " parses " + rate(m.jclRate())
                    + " of its JCL, below the pinned " + rate(pinned.jclRate()));
            assertTrue(m.sqlRate() >= pinned.sqlRate(), m.name() + " parses " + rate(m.sqlRate())
                    + " of its SQL, below the pinned " + rate(pinned.sqlRate()));
            assertTrue(m.jclFailed() <= pinned.jclFilesFailed(), m.name() + " loses " + m.jclFailed()
                    + " JCL files whole, more than the pinned " + pinned.jclFilesFailed());
            assertTrue(m.sqlSetAside() <= pinned.sqlSetAside(), m.name() + " sets aside "
                    + m.sqlSetAside() + " SQL statements, more than the pinned " + pinned.sqlSetAside());
            assertTrue(m.scriptDegraded() <= pinned.scriptDegraded(), m.name() + " reads "
                    + m.scriptDegraded() + " script statements only in part, more than the pinned "
                    + pinned.scriptDegraded());
            atLeast(m.name(), "JCL files", m.jclFiles(), pinned.jclFiles());
            atLeast(m.name(), "JCL files with a job model", m.jclWithModel(), pinned.jclWithModel());
            atLeast(m.name(), "SQL statements read in full", m.sqlAnalysed(), pinned.sqlAnalysed());
            atLeast(m.name(), "script statements read in full", m.scriptAnalysed(),
                    pinned.scriptAnalysed());
            atMost(m.name(), "JCL files read as a member", m.jclSkipped(), pinned.jclSkipped());
            atMost(m.name(), "files of undecided kind", m.undecided(), pinned.undecided());
            atMost(m.name(), "COBOL files lost whole", m.cobolFailed(), pinned.cobolFailed());
            atMost(m.name(), "JCL statements not understood", m.jclStatementsLost(),
                    pinned.jclStatementsLost());
            atMost(m.name(), "JCL parameters kept as raw text", m.jclParametersRaw(),
                    pinned.jclParametersRaw());
        }
    }

    /** A count that may grow but not shrink: what the folder is read for. */
    private static void atLeast(String folder, String what, int measured, int pinned) {
        assertTrue(measured >= pinned, folder + " holds " + measured + " " + what
                + ", below the pinned " + pinned);
    }

    /** A count that may shrink but not grow: what the folder loses. */
    private static void atMost(String folder, String what, int measured, int pinned) {
        assertTrue(measured <= pinned, folder + " holds " + measured + " " + what
                + ", above the pinned " + pinned);
    }

    // ---- measurement ----

    /** The corpus folders, plus whatever COBOL_INSIGHT_BENCH_DIR names when it names something. */
    private static List<Folder> folders() {
        List<Folder> folders = new ArrayList<>(List.of(
                new Folder("corpus-constructs", REPO.resolve("corpus-constructs")),
                new Folder("corpus-public", REPO.resolve("corpus-public"))));
        String bench = System.getenv("COBOL_INSIGHT_BENCH_DIR");
        if (bench != null && !bench.isBlank()) {
            folders.add(new Folder("bench", Path.of(bench).toAbsolutePath().normalize()));
        }
        return folders;
    }

    private static Metrics measure(Folder folder) {
        Set<AssetKind> allKinds = EnumSet.allOf(AssetKind.class);
        SourceSet s = new SourceSet(new SourceSet.Options(folder.dir(), UNUSED_DATABASE,
                copybookPaths(folder), Map.of(), RuleSet.load((Path) null), Set.of(Needs.SQL)));
        Pipeline.run(List.of(new Discover(), new Classify(allKinds, false), new Decode(allKinds),
                new Parse(), new Semantic()), s);

        int jclFiles = 0;
        int jclWithModel = 0;
        int jclSkipped = 0;
        int jclFailed = 0;
        int cobolFiles = 0;
        int cobolFailed = 0;
        int jclStatementsLost = 0;
        int jclParametersRaw = 0;
        int jclDirectives = 0;
        Map<AssetKind, Integer> parseFailures = new EnumMap<>(AssetKind.class);
        List<Failure> failures = new ArrayList<>();
        for (SourceUnit unit : s.units()) {
            boolean hasModel = s.jobsByPath().containsKey(unit.relPath())
                    || s.programsByPath().containsKey(unit.relPath());
            boolean failed = s.unanalyzable().containsKey(unit.relPath());
            if (unit.kind() == AssetKind.JCL) {
                jclFiles++;
                jclWithModel += hasModel ? 1 : 0;
                jclFailed += failed ? 1 : 0;
                jclSkipped += !hasModel && !failed ? 1 : 0;
            }
            if (unit.kind() == AssetKind.COBOL) {
                cobolFiles++;
                cobolFailed += failed ? 1 : 0;
            }
            for (Finding finding : s.findingsOf(unit.relPath())) {
                if (Finding.PARSE_FAILURE_RULE_ID.equals(finding.ruleId())) {
                    parseFailures.merge(unit.kind(), 1, Integer::sum);
                }
                if (Finding.JCL_DIRECTIVE_RULE_ID.equals(finding.ruleId())) {
                    // A scheduler marker is read past on purpose; it costs no statement.
                    jclDirectives++;
                    continue;
                }
                boolean jclSyntax = Finding.JCL_SYNTAX_RULE_ID.equals(finding.ruleId());
                boolean salvaged = isSalvagedParameter(finding);
                jclStatementsLost += jclSyntax && !salvaged ? 1 : 0;
                jclParametersRaw += salvaged ? 1 : 0;
                failures.add(new Failure(unit.relPath(), finding.location().line(),
                        unit.kind() + " " + finding.ruleId(), finding.message(),
                        taxonomyOf(finding)));
            }
        }
        // The rate measures the EXEC SQL of the programs, so the statements of an SQL script are
        // counted apart: a script holds whole DDL, which is not the same coverage question.
        Map<String, List<SqlStatementModel>> scripts = s.sqlByScript();
        int sqlAnalysed = 0;
        int sqlDegraded = 0;
        int scriptAnalysed = 0;
        int scriptDegraded = 0;
        for (Map.Entry<String, List<SqlStatementModel>> entry : s.sqlByPath().entrySet()) {
            boolean script = scripts.containsKey(entry.getKey());
            for (SqlStatementModel statement : entry.getValue()) {
                if (script) {
                    scriptAnalysed += statement.isFullyAnalysed() ? 1 : 0;
                    scriptDegraded += statement.isFullyAnalysed() ? 0 : 1;
                } else {
                    sqlAnalysed += statement.isFullyAnalysed() ? 1 : 0;
                    sqlDegraded += statement.isFullyAnalysed() ? 0 : 1;
                }
            }
        }
        // Every EXEC SQL block of a parsed program should have produced a model. What did not is
        // set aside, and there is meant to be none of it. Today none of it is structural rather
        // than measured — the one SQL frontend never answers with a failure — so this stands as an
        // invariant against a frontend that does, not as a coverage measure. What holds coverage
        // is the sqlAnalysed floor: a block the model stops reporting leaves this difference at 0
        // and takes the count down with it.
        int sqlSetAside = sqlBlocks(s) - sqlAnalysed - sqlDegraded;
        failures.sort(Comparator.comparing(Failure::file).thenComparingInt(Failure::line));

        return new Metrics(folder.name(), jclFiles, jclWithModel, jclSkipped, jclFailed,
                jclStatementsLost, jclParametersRaw, jclDirectives, cobolFiles, cobolFailed,
                sqlAnalysed, sqlDegraded, sqlSetAside, s.unitsOf(AssetKind.SQL).size(),
                scriptAnalysed, scriptDegraded, s.discovery().undecided().size(), parseFailures,
                failures);
    }

    private static boolean isSalvagedParameter(Finding finding) {
        return Finding.JCL_SYNTAX_RULE_ID.equals(finding.ruleId())
                && finding.message().contains(SALVAGED_PARAMETER);
    }

    /** How a pipeline finding is classified in the failures table. */
    private static String taxonomyOf(Finding finding) {
        if (Finding.JCL_SYNTAX_RULE_ID.equals(finding.ruleId())) {
            return isSalvagedParameter(finding) ? "salvaged parameter" : "unsupported statement";
        }
        if (Finding.SQL_SYNTAX_RULE_ID.equals(finding.ruleId())) {
            return "unsupported SQL";
        }
        return "unclassified";
    }

    /** Every EXEC SQL block the parsed programs hold. */
    private static int sqlBlocks(SourceSet s) {
        int blocks = 0;
        for (CobolSemanticModel program : s.programsByPath().values()) {
            for (EmbeddedBlock block : program.embeddedBlocks()) {
                blocks += block.kind() == EmbeddedBlockKind.SQL ? 1 : 0;
            }
        }
        return blocks;
    }

    /**
     * The COPY search paths of a folder. corpus-constructs is laid out by hand, so its two source
     * folders are named; anywhere else, wherever the walk found copybooks becomes the search path —
     * the rule the CLI applies when nobody passes {@code --copybook-path}.
     */
    private static List<Path> copybookPaths(Folder folder) {
        if (folder.name().equals("corpus-constructs")) {
            return Arrays.stream(new Path[] {folder.dir().resolve("sql"),
                    folder.dir().resolve("cobol")}).filter(Files::isDirectory).toList();
        }
        Set<Path> parents = new LinkedHashSet<>();
        for (SourceDiscovery.DiscoveredFile file
                : SourceDiscovery.discover(folder.dir()).filesOf(Set.of(AssetKind.COPYBOOK))) {
            Path parent = file.absPath().getParent();
            if (parent != null) {
                parents.add(parent);
            }
        }
        return List.copyOf(parents);
    }

    // ---- report ----

    /**
     * Where the report goes: corpus-public when that folder exists, otherwise corpus-constructs.
     * With neither folder on disk nothing was measured, so nothing is written.
     */
    private static Path reportFile() {
        for (String name : List.of("corpus-public", "corpus-constructs")) {
            Path dir = REPO.resolve(name);
            if (Files.isDirectory(dir)) {
                return dir.resolve("parse-report.md");
            }
        }
        return null;
    }

    private static final String EMPTY_REPORT = """
            # Parse coverage

            How much of each corpus folder the engine parses, measured by ParseRateReportTest.
            Everything between the markers is rewritten on every run; prose around them is kept.

            <!-- generated by ParseRateReportTest: begin -->
            <!-- generated by ParseRateReportTest: end -->
            """;

    private static void writeReport() throws IOException {
        Path report = reportFile();
        if (report == null) {
            System.out.println("ParseRateReportTest: no corpus folder on disk, no report written");
            return;
        }
        String existing = Files.exists(report)
                ? Files.readString(report, StandardCharsets.UTF_8) : EMPTY_REPORT;
        int begin = existing.indexOf(BEGIN);
        int end = existing.indexOf(END);
        if (begin < 0 || end < 0) {
            throw new IllegalStateException(report + " must carry the generated-section markers");
        }
        String rewritten = existing.substring(0, begin + BEGIN.length()) + "\n\n" + body() + "\n"
                + existing.substring(end);
        if (!rewritten.equals(existing)) {
            Files.writeString(report, rewritten, StandardCharsets.UTF_8);
        }
    }

    private static String body() {
        StringBuilder out = new StringBuilder();
        for (Metrics m : measured) {
            out.append("## ").append(m.name()).append("\n\n")
                    .append("| measure | count |\n|---|--:|\n")
                    .append(row("JCL files discovered", m.jclFiles()))
                    .append(row("JCL files with a job model", m.jclWithModel()))
                    .append(row("JCL members skipped (no JOB card)", m.jclSkipped()))
                    .append(row("JCL files failed", m.jclFailed()))
                    .append(row("JCL statements not understood", m.jclStatementsLost()))
                    .append(row("JCL parameters kept as raw text", m.jclParametersRaw()))
                    .append(row("scheduler directive lines", m.jclDirectives()))
                    .append(row("COBOL files discovered", m.cobolFiles()))
                    .append(row("COBOL files failed", m.cobolFailed()))
                    .append(row("SQL statements analysed", m.sqlAnalysed()))
                    .append(row("SQL statements degraded", m.sqlDegraded()))
                    .append(row("SQL statements set aside", m.sqlSetAside()))
                    .append(row("SQL scripts discovered", m.scriptFiles()))
                    .append(row("SQL script statements analysed", m.scriptAnalysed()))
                    .append(row("SQL script statements degraded", m.scriptDegraded()))
                    .append(row("files of undecided kind", m.undecided()))
                    .append("| parse-failure findings | ")
                    .append(m.parseFailures().isEmpty() ? "0" : m.parseFailures().toString())
                    .append(" |\n")
                    .append("| JCL file rate | ").append(rate(m.jclRate())).append(" |\n")
                    .append("| SQL statement rate | ").append(rate(m.sqlRate())).append(" |\n\n");
        }
        out.append("## Failures and set-aside statements\n\n")
                .append("A JCL statement the parser recovered from is tagged `unsupported "
                        + "statement`, one whose statement was read and whose single parameter "
                        + "stayed raw text `salvaged parameter`, an SQL statement — embedded or "
                        + "from a script — the tool could read only in part `unsupported SQL`; "
                        + "every other row stays `unclassified` until the construct behind it is "
                        + "tagged.\n\n")
                .append("| folder | file | line | what | message | taxonomy |\n")
                .append("|---|---|--:|---|---|---|\n");
        for (Metrics m : measured) {
            for (Failure f : m.failures()) {
                out.append("| ").append(m.name()).append(" | ").append(f.file())
                        .append(" | ").append(f.line()).append(" | ").append(f.what())
                        .append(" | ").append(cell(f.message())).append(" | ")
                        .append(f.taxonomy()).append(" |\n");
            }
        }
        return out.toString();
    }

    private static String row(String label, int count) {
        return "| " + label + " | " + count + " |\n";
    }

    private static String rate(double value) {
        return String.format(Locale.ROOT, "%.3f", value);
    }

    /**
     * A finding message inside a Markdown table cell: one line, no cell break, and no absolute
     * path — the report is committed, so a machine's own checkout directory must not reach it.
     * A parser that could not go on quotes everything it had left, which runs to a thousand
     * characters; the head of it says which construct broke, and that is what the column is for.
     */
    private static String cell(String message) {
        String text = message.replace(REPO + File.separator, "")
                .replace("|", "\\|").replaceAll("\\s+", " ").strip();
        return text.length() <= 200 ? text : text.substring(0, 200) + " …";
    }
}
